"use client";

import { useState } from "react";
import { v4 as uuidv4 } from "uuid";

/**
 * A larger fake product catalog for development & testing.
 * Each product includes many fields used by the UI (price, images, vendor, tags, deliveryTime, etc).
 */

/* --- Generated sample products --- */
const initialProducts = [
  {
    id: uuidv4(),
    name: "Seedless Prunes",
    slug: "seedless-prunes",
    category: "Fruits & Vegetables",
    price: 3200,
    originalPrice: 4000,
    rating: 4.9,
    reviewCount: 127,
    weight: "1.1 kg",
    image: "/images/products/seedless-prunes.jpg",
    images: [
      "/images/products/seedless-prunes-1.jpg",
      "/images/products/seedless-prunes-2.jpg",
    ],
    onSale: true,
    discountPercent: 20,
    stock: 45,
    isOrganic: true,
    isFresh: true,
    brand: "Mighty Square",
    vendor: {
      id: uuidv4(),
      name: "Fresh Farms Co.",
      logo: "/images/vendors/fresh-farms.png",
      rating: 4.8,
    },
    nutritionFacts: {
      calories: 240,
      protein: "2g",
      carbs: "65g",
      fat: "0.5g",
    },
    tags: ["organic", "vegan", "gluten-free"],
    deliveryTime: "2-4 hours",
    description: "Premium quality seedless prunes, naturally sweet and nutritious.",
  },

  {
    id: uuidv4(),
    name: "Black-eyed Peas with Extra Raisins",
    slug: "black-eyed-peas-extra-raisins",
    category: "Grains & Pasta",
    price: 2200,
    originalPrice: 2600,
    rating: 3.3,
    reviewCount: 54,
    weight: "2.2 kg",
    image: "/images/products/black-eyed-peas.jpg",
    images: [
      "/images/products/black-eyed-peas-1.jpg",
      "/images/products/black-eyed-peas-2.jpg",
    ],
    onSale: false,
    discountPercent: 0,
    stock: 20,
    isOrganic: false,
    isFresh: true,
    brand: "Amboseli",
    vendor: {
      id: uuidv4(),
      name: "Amboseli Farms",
      logo: "/images/vendors/amboseli.png",
      rating: 4.5,
    },
    nutritionFacts: {
      calories: 180,
      protein: "3g",
      carbs: "40g",
      fat: "0.2g",
    },
    tags: ["vegan", "gluten-free"],
    deliveryTime: "2-4 hours",
    description: "Extra raisins for a sweet and healthy snack.",
  },

  {
    id: uuidv4(),
    name: "Fresh Ripe Tomatoes (1.5 kg)",
    slug: "fresh-ripe-tomatoes-1-5kg",
    category: "Fruits & Vegetables",
    price: 900,
    originalPrice: 1100,
    rating: 4.4,
    reviewCount: 78,
    weight: "1.5 kg",
    image: "/images/products/tomatoes.jpg",
    images: ["/images/products/tomatoes-1.jpg"],
    onSale: true,
    discountPercent: 18,
    stock: 120,
    isOrganic: false,
    isFresh: true,
    brand: "Green Valley",
    vendor: {
      id: uuidv4(),
      name: "Green Valley Produce",
      logo: "/images/vendors/green-valley.png",
      rating: 4.6,
    },
    nutritionFacts: {
      calories: 22,
      protein: "1g",
      carbs: "4g",
      fat: "0.2g",
    },
    tags: ["fresh", "local"],
    deliveryTime: "1-3 hours",
    description: "Juicy, vine-ripened tomatoes — perfect for salads and sauces.",
  },

  {
    id: uuidv4(),
    name: "Wholegrain Bread (600g)",
    slug: "wholegrain-bread-600g",
    category: "Bakery",
    price: 650,
    originalPrice: 800,
    rating: 4.2,
    reviewCount: 210,
    weight: "600 g",
    image: "/images/products/wholegrain-bread.jpg",
    images: ["/images/products/wholegrain-bread-1.jpg"],
    onSale: true,
    discountPercent: 19,
    stock: 60,
    isOrganic: false,
    isFresh: true,
    brand: "Daily Loaf",
    vendor: {
      id: uuidv4(),
      name: "Daily Loaf Bakery",
      logo: "/images/vendors/daily-loaf.png",
      rating: 4.4,
    },
    nutritionFacts: {
      calories: 220,
      protein: "7g",
      carbs: "38g",
      fat: "3g",
    },
    tags: ["bakery", "wholegrain"],
    deliveryTime: "2-4 hours",
    description: "Soft, nutritious wholegrain bread baked fresh daily.",
  },

  {
    id: uuidv4(),
    name: "Pure Honey (500g)",
    slug: "pure-honey-500g",
    category: "Beverages",
    price: 2800,
    originalPrice: 3200,
    rating: 4.7,
    reviewCount: 95,
    weight: "500 g",
    image: "/images/products/honey.jpg",
    images: ["/images/products/honey-1.jpg"],
    onSale: false,
    discountPercent: 0,
    stock: 80,
    isOrganic: true,
    isFresh: false,
    brand: "Golden Nectar",
    vendor: {
      id: uuidv4(),
      name: "Golden Nectar Ltd.",
      logo: "/images/vendors/golden-nectar.png",
      rating: 4.9,
    },
    nutritionFacts: {
      calories: 300,
      protein: "0.3g",
      carbs: "82g",
      fat: "0g",
    },
    tags: ["organic", "natural", "sweetener"],
    deliveryTime: "2-5 hours",
    description: "Single-origin pure honey with floral notes.",
  },

  {
    id: uuidv4(),
    name: "UHT Milk Full Cream (1L)",
    slug: "uht-milk-full-cream-1l",
    category: "Dairy & Eggs",
    price: 750,
    originalPrice: 900,
    rating: 4.1,
    reviewCount: 310,
    weight: "1 L",
    image: "/images/products/milk-1l.jpg",
    images: ["/images/products/milk-1l-1.jpg"],
    onSale: true,
    discountPercent: 16,
    stock: 200,
    isOrganic: false,
    isFresh: false,
    brand: "PureDairy",
    vendor: {
      id: uuidv4(),
      name: "PureDairy Co.",
      logo: "/images/vendors/puredairy.png",
      rating: 4.3,
    },
    nutritionFacts: {
      calories: 150,
      protein: "8g",
      carbs: "12g",
      fat: "8g",
    },
    tags: ["dairy", "calcium"],
    deliveryTime: "2-4 hours",
    description: "Full cream UHT milk — long shelf-life and nutritious.",
  },

  {
    id: uuidv4(),
    name: "Indomie Instant Noodles (5-pack)",
    slug: "indomie-instant-noodles-5-pack",
    category: "Snacks",
    price: 1200,
    originalPrice: 1500,
    rating: 4.5,
    reviewCount: 840,
    weight: "400 g",
    image: "/images/products/indomie-5pack.jpg",
    images: ["/images/products/indomie-1.jpg"],
    onSale: false,
    discountPercent: 0,
    stock: 500,
    isOrganic: false,
    isFresh: false,
    brand: "Indomie",
    vendor: {
      id: uuidv4(),
      name: "Dufil Prima Foods",
      logo: "/images/vendors/dufil-prima.png",
      rating: 4.2,
    },
    nutritionFacts: {
      calories: 380,
      protein: "9g",
      carbs: "54g",
      fat: "12g",
    },
    tags: ["instant", "pantry"],
    deliveryTime: "1-3 hours",
    description: "Popular instant noodles — quick and tasty.",
  },

  {
    id: uuidv4(),
    name: "Frozen Chicken (Whole, 1.6kg)",
    slug: "frozen-chicken-whole-1-6kg",
    category: "Frozen Foods",
    price: 5500,
    originalPrice: 6200,
    rating: 4.6,
    reviewCount: 412,
    weight: "1.6 kg",
    image: "/images/products/frozen-chicken.jpg",
    images: ["/images/products/frozen-chicken-1.jpg"],
    onSale: true,
    discountPercent: 11,
    stock: 70,
    isOrganic: false,
    isFresh: false,
    brand: "FarmFresh Frozen",
    vendor: {
      id: uuidv4(),
      name: "ColdChain Foods",
      logo: "/images/vendors/coldchain.png",
      rating: 4.4,
    },
    nutritionFacts: {
      calories: 220,
      protein: "25g",
      carbs: "0g",
      fat: "12g",
    },
    tags: ["protein", "frozen"],
    deliveryTime: "2-4 hours",
    description: "Whole chilled chicken, vacuum packed and frozen for freshness.",
  },

  {
    id: uuidv4(),
    name: "Olive Oil Extra Virgin (750ml)",
    slug: "olive-oil-extra-virgin-750ml",
    category: "Spices & Condiments",
    price: 7200,
    originalPrice: 9000,
    rating: 4.8,
    reviewCount: 210,
    weight: "750 ml",
    image: "/images/products/olive-oil.jpg",
    images: ["/images/products/olive-oil-1.jpg"],
    onSale: true,
    discountPercent: 20,
    stock: 36,
    isOrganic: true,
    isFresh: false,
    brand: "Casa Verde",
    vendor: {
      id: uuidv4(),
      name: "Casa Verde Imports",
      logo: "/images/vendors/casa-verde.png",
      rating: 4.7,
    },
    nutritionFacts: {
      calories: 884,
      protein: "0g",
      carbs: "0g",
      fat: "100g",
    },
    tags: ["organic", "cooking"],
    deliveryTime: "2-5 hours",
    description: "Cold pressed extra virgin olive oil for healthy cooking.",
  },

  {
    id: uuidv4(),
    name: "Chocolate Bars (Pack of 6)",
    slug: "chocolate-bars-pack-6",
    category: "Snacks",
    price: 1800,
    originalPrice: 2200,
    rating: 4.0,
    reviewCount: 156,
    weight: "360 g",
    image: "/images/products/chocolate-pack.jpg",
    images: ["/images/products/chocolate-pack-1.jpg"],
    onSale: false,
    discountPercent: 0,
    stock: 260,
    isOrganic: false,
    isFresh: false,
    brand: "CocoaDelight",
    vendor: {
      id: uuidv4(),
      name: "Sweet Treats Ltd.",
      logo: "/images/vendors/sweet-treats.png",
      rating: 4.2,
    },
    nutritionFacts: {
      calories: 540,
      protein: "6g",
      carbs: "58g",
      fat: "30g",
    },
    tags: ["snack", "sweet"],
    deliveryTime: "1-3 hours",
    description: "Assorted chocolate bars perfect for gifting and snacking.",
  },

  {
    id: uuidv4(),
    name: "Organic Baby Spinach (200g)",
    slug: "organic-baby-spinach-200g",
    category: "Fruits & Vegetables",
    price: 650,
    originalPrice: 800,
    rating: 4.5,
    reviewCount: 66,
    weight: "200 g",
    image: "/images/products/baby-spinach.jpg",
    images: ["/images/products/baby-spinach-1.jpg"],
    onSale: false,
    discountPercent: 0,
    stock: 140,
    isOrganic: true,
    isFresh: true,
    brand: "Leaf & Co",
    vendor: {
      id: uuidv4(),
      name: "Leaf & Co Farms",
      logo: "/images/vendors/leaf-co.png",
      rating: 4.6,
    },
    nutritionFacts: {
      calories: 23,
      protein: "2.9g",
      carbs: "3.6g",
      fat: "0.4g",
    },
    tags: ["organic", "vegan", "leafy"],
    deliveryTime: "1-2 hours",
    description: "Fresh organic baby spinach leaves ready for salads and cooking.",
  },

  {
    id: uuidv4(),
    name: "Greek Yogurt (Plain, 400g)",
    slug: "greek-yogurt-plain-400g",
    category: "Dairy & Eggs",
    price: 1200,
    originalPrice: 1400,
    rating: 4.6,
    reviewCount: 180,
    weight: "400 g",
    image: "/images/products/greek-yogurt.jpg",
    images: ["/images/products/greek-yogurt-1.jpg"],
    onSale: false,
    discountPercent: 0,
    stock: 110,
    isOrganic: false,
    isFresh: true,
    brand: "YumGreek",
    vendor: {
      id: uuidv4(),
      name: "YumGreek Dairy",
      logo: "/images/vendors/yumgreek.png",
      rating: 4.5,
    },
    nutritionFacts: {
      calories: 120,
      protein: "10g",
      carbs: "6g",
      fat: "5g",
    },
    tags: ["probiotic", "high-protein"],
    deliveryTime: "2-4 hours",
    description: "Creamy Greek yogurt, perfect for breakfast and smoothies.",
  },

  {
    id: uuidv4(),
    name: "Toothpaste Whitening (100ml)",
    slug: "toothpaste-whitening-100ml",
    category: "Personal Care",
    price: 650,
    originalPrice: 850,
    rating: 4.0,
    reviewCount: 58,
    weight: "100 ml",
    image: "/images/products/toothpaste.jpg",
    images: ["/images/products/toothpaste-1.jpg"],
    onSale: true,
    discountPercent: 24,
    stock: 320,
    isOrganic: false,
    isFresh: false,
    brand: "BrightSmile",
    vendor: {
      id: uuidv4(),
      name: "BrightCare",
      logo: "/images/vendors/brightcare.png",
      rating: 4.1,
    },
    nutritionFacts: null,
    tags: ["personal-care", "oral-care"],
    deliveryTime: "1-3 hours",
    description: "Whitening toothpaste with fluoride for daily use.",
  },

  {
    id: uuidv4(),
    name: "Baby Diapers (Size M, 30pcs)",
    slug: "baby-diapers-size-m-30pcs",
    category: "Baby Products",
    price: 4800,
    originalPrice: 5200,
    rating: 4.3,
    reviewCount: 220,
    weight: "1.2 kg",
    image: "/images/products/diapers.jpg",
    images: ["/images/products/diapers-1.jpg"],
    onSale: false,
    discountPercent: 0,
    stock: 150,
    isOrganic: false,
    isFresh: false,
    brand: "GentleBaby",
    vendor: {
      id: uuidv4(),
      name: "GentleBaby Supplies",
      logo: "/images/vendors/gentlebaby.png",
      rating: 4.4,
    },
    nutritionFacts: null,
    tags: ["baby", "essential"],
    deliveryTime: "2-4 hours",
    description: "Soft and absorbent diapers for comfortable wear.",
  },

  {
    id: uuidv4(),
    name: "Multivitamin Tablets (30pcs)",
    slug: "multivitamin-tablets-30pcs",
    category: "Health & Wellness",
    price: 3000,
    originalPrice: 3500,
    rating: 4.2,
    reviewCount: 90,
    weight: "120 g",
    image: "/images/products/multivitamin.jpg",
    images: ["/images/products/multivitamin-1.jpg"],
    onSale: false,
    discountPercent: 0,
    stock: 210,
    isOrganic: false,
    isFresh: false,
    brand: "VitaPlus",
    vendor: {
      id: uuidv4(),
      name: "Healthline Pharma",
      logo: "/images/vendors/healthline.png",
      rating: 4.5,
    },
    nutritionFacts: null,
    tags: ["health", "supplement"],
    deliveryTime: "2-5 hours",
    description: "Daily multivitamin to support general wellbeing.",
  },

  {
    id: uuidv4(),
    name: "Fresh Apples (1 kg)",
    slug: "fresh-apples-1kg",
    category: "Fruits & Vegetables",
    price: 1200,
    originalPrice: 1500,
    rating: 4.5,
    reviewCount: 312,
    weight: "1 kg",
    image: "/images/products/apples.jpg",
    images: ["/images/products/apples-1.jpg"],
    onSale: true,
    discountPercent: 20,
    stock: 180,
    isOrganic: false,
    isFresh: true,
    brand: "Orchard Best",
    vendor: {
      id: uuidv4(),
      name: "Orchard Best Ltd.",
      logo: "/images/vendors/orchard-best.png",
      rating: 4.6,
    },
    nutritionFacts: {
      calories: 52,
      protein: "0.3g",
      carbs: "14g",
      fat: "0.2g",
    },
    tags: ["fresh", "snack"],
    deliveryTime: "1-2 hours",
    description: "Crisp and sweet apples — perfect for snacking.",
  },

  {
    id: uuidv4(),
    name: "Tomato Paste (400g)",
    slug: "tomato-paste-400g",
    category: "Spices & Condiments",
    price: 450,
    originalPrice: 600,
    rating: 4.0,
    reviewCount: 48,
    weight: "400 g",
    image: "/images/products/tomato-paste.jpg",
    images: ["/images/products/tomato-paste-1.jpg"],
    onSale: false,
    discountPercent: 0,
    stock: 420,
    isOrganic: false,
    isFresh: false,
    brand: "RedGold",
    vendor: {
      id: uuidv4(),
      name: "RedGold Foods",
      logo: "/images/vendors/redgold.png",
      rating: 4.1,
    },
    nutritionFacts: {
      calories: 82,
      protein: "2g",
      carbs: "19g",
      fat: "0.5g",
    },
    tags: ["pantry", "cooking"],
    deliveryTime: "1-3 hours",
    description: "Concentrated tomato paste for sauces and stews.",
  },

  {
    id: uuidv4(),
    name: "Mixed Fruit Jam (350g)",
    slug: "mixed-fruit-jam-350g",
    category: "Bakery",
    price: 950,
    originalPrice: 1100,
    rating: 4.3,
    reviewCount: 62,
    weight: "350 g",
    image: "/images/products/fruit-jam.jpg",
    images: ["/images/products/fruit-jam-1.jpg"],
    onSale: false,
    discountPercent: 0,
    stock: 140,
    isOrganic: false,
    isFresh: false,
    brand: "SunnyPreserve",
    vendor: {
      id: uuidv4(),
      name: "SunnyPreserve Co.",
      logo: "/images/vendors/sunnypreserve.png",
      rating: 4.4,
    },
    nutritionFacts: {
      calories: 260,
      protein: "0g",
      carbs: "66g",
      fat: "0g",
    },
    tags: ["breakfast", "spreads"],
    deliveryTime: "2-4 hours",
    description: "Sweet and tangy mixed fruit jam for toast and pastries.",
  },

  {
    id: uuidv4(),
    name: "Brown Rice (5 kg)",
    slug: "brown-rice-5kg",
    category: "Grains & Pasta",
    price: 8200,
    originalPrice: 9800,
    rating: 4.4,
    reviewCount: 48,
    weight: "5 kg",
    image: "/images/products/brown-rice.jpg",
    images: ["/images/products/brown-rice-1.jpg"],
    onSale: true,
    discountPercent: 16,
    stock: 90,
    isOrganic: false,
    isFresh: false,
    brand: "FarmField",
    vendor: {
      id: uuidv4(),
      name: "FarmField Supplies",
      logo: "/images/vendors/farmfield.png",
      rating: 4.5,
    },
    nutritionFacts: {
      calories: 111,
      protein: "2.6g",
      carbs: "23g",
      fat: "0.9g",
    },
    tags: ["staple", "healthy"],
    deliveryTime: "2-5 hours",
    description: "Premium brown rice — healthy and high in fiber.",
  },

  {
    id: uuidv4(),
    name: "Sparkling Water (1.5L)",
    slug: "sparkling-water-1-5l",
    category: "Beverages",
    price: 450,
    originalPrice: 600,
    rating: 4.2,
    reviewCount: 34,
    weight: "1.5 L",
    image: "/images/products/sparkling-water.jpg",
    images: ["/images/products/sparkling-water-1.jpg"],
    onSale: false,
    discountPercent: 0,
    stock: 300,
    isOrganic: false,
    isFresh: false,
    brand: "AquaFiz",
    vendor: {
      id: uuidv4(),
      name: "AquaFiz Ltd.",
      logo: "/images/vendors/aquafiz.png",
      rating: 4.0,
    },
    nutritionFacts: {
      calories: 0,
      protein: "0g",
      carbs: "0g",
      fat: "0g",
    },
    tags: ["beverage", "hydration"],
    deliveryTime: "1-2 hours",
    description: "Lightly carbonated sparkling water — refreshing and calorie-free.",
  },

  {
    id: uuidv4(),
    name: "Peanut Butter Crunchy (400g)",
    slug: "peanut-butter-crunchy-400g",
    category: "Snacks",
    price: 2300,
    originalPrice: 2700,
    rating: 4.6,
    reviewCount: 145,
    weight: "400 g",
    image: "/images/products/peanut-butter.jpg",
    images: ["/images/products/peanut-butter-1.jpg"],
    onSale: false,
    discountPercent: 0,
    stock: 210,
    isOrganic: false,
    isFresh: false,
    brand: "NutriSpread",
    vendor: {
      id: uuidv4(),
      name: "NutriSpread Co.",
      logo: "/images/vendors/nutrispread.png",
      rating: 4.6,
    },
    nutritionFacts: {
      calories: 588,
      protein: "25g",
      carbs: "20g",
      fat: "50g",
    },
    tags: ["spread", "protein"],
    deliveryTime: "1-3 hours",
    description: "Crunchy peanut butter made from roasted peanuts.",
  },

  {
    id: uuidv4(),
    name: "Herbal Tea Assorted (20 teabags)",
    slug: "herbal-tea-assorted-20-teabags",
    category: "Beverages",
    price: 950,
    originalPrice: 1100,
    rating: 4.3,
    reviewCount: 40,
    weight: "40 g",
    image: "/images/products/herbal-tea.jpg",
    images: ["/images/products/herbal-tea-1.jpg"],
    onSale: false,
    discountPercent: 0,
    stock: 130,
    isOrganic: true,
    isFresh: false,
    brand: "HerbAroma",
    vendor: {
      id: uuidv4(),
      name: "HerbAroma Naturals",
      logo: "/images/vendors/herbaroma.png",
      rating: 4.5,
    },
    nutritionFacts: null,
    tags: ["tea", "organic"],
    deliveryTime: "2-4 hours",
    description: "Calming herbal tea assortment for daily relaxation.",
  },
];

/* --- Hook to manage products dynamically (keeps previous API) --- */
export function useProducts() {
  const [products, setProducts] = useState(initialProducts);

  // Add a new product dynamically
  const addProduct = (product) => {
    const newProduct = {
      ...product,
      id: uuidv4(),
      currency: "NGN",
      vendor: {
        id: product.vendor?.id || uuidv4(),
        ...product.vendor,
      },
    };
    setProducts((prev) => [newProduct, ...prev]);
  };

  // Update product (simple replace by id)
  const updateProduct = (id, patch) => {
    setProducts((prev) => prev.map((p) => (p.id === id ? { ...p, ...patch } : p)));
  };

  // Remove product by id
  const removeProduct = (id) => {
    setProducts((prev) => prev.filter((p) => p.id !== id));
  };

  // Simulate async fetching
  const fetchProducts = async () => {
    // small artificial delay
    await new Promise((resolve) => setTimeout(resolve, 200));
    return products;
  };

  return { products, addProduct, updateProduct, removeProduct, fetchProducts, setProducts };
}